# Generated by Django 5.0.1 on 2024-01-06 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="is_superuser",
        ),
    ]
