# Generated by Django 5.0.1 on 2024-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Productname", models.CharField(max_length=50)),
                ("Productprice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
